### PR TITLE
REF-322 Replicated files contain HTTP headers

### LINKED ISSUE #322: [CDF] Replicated files contain HTTP headers
**Describe the bug**
When running replication from DDF to HDFS, the replicated files contain metadata that should not be there.

This is likely related to the MultipartEntityBuilder used in writeFileToLocation. This could have to do with the MultipartEntityBuilder setting the content type but not positive. 

In this ticket, removing the headers that are corrupting the file should be investigated and fixed.

**Affects version**
0.3.x

**To Reproduce**
1. Set up replication on a DDF Instance
2. Ingest a file with text in it.
3. Go to the HDFS cluster and view the file (download or view the content). There will be added http headers before the ingested file's content.

**Expected behavior**
No headers should be in the file content.

### PR DESCRIPTION
**Pull request by josephthweatt**
#### What does this PR do?
Removes headers in files uploaded to HDFS. 

#### Who is reviewing it 
@mdang8 
@cjlange 

#### How should this be tested? (List steps with links to updated documentation)
1. Build branch and add to a running DDF instance. Follow normal instructions to set up Replication between DDF and a local Hdfs node.
2. Ingest a file to DDF. Once replication has uploaded the file to hdfs, go onto hdfs' webpage and view the file. 
3. Download or select "tail from head" to view the content. Verify there are no headers before or after the original file content.

#### What are the relevant tickets?
Fixes #322 

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by josephthweatt** [comment]
build now

File: adapters/webhdfs-adapter/src/main/java/com/connexta/replication/adapters/webhdfs/WebHdfsNodeAdapter.java [hunk 1]
```diff
@@ -302,7 +305,10 @@ boolean writeFileToLocation(CreateStorageRequest createStorageRequest, String lo
           }
         };
 
-    return sendHttpRequest(httpPut, responseHandler);
+    boolean successful = sendHttpRequest(httpPut, responseHandler);
```
Comment (aaronilovici) [inline adapters/webhdfs-adapter/src/main/java/com/connexta/replication/adapters/webhdfs/WebHdfsNodeAdapter.java]: Can you declare this boolean above the try{}
Then put this in the try{}: successful = sendHttpRequest(httpPut, responseHandler)
So that the tempFile.delete() can happen in a finally{}?

I see that you do deleteOnExit but I think that only carries when the program or JVM closes, but this is meant to be a long running process so we could, in an error state, and up with a lot of temp files that never got deleted.

As it stands now if there is an IOException in the try, after the temp files is created, the temp file wouldn't be deleted until the JVM shuts down.

**Review by aaronilovici — APPROVED** [review]

**Comment by josephthweatt** [comment]
build now

File: adapters/webhdfs-adapter/src/test/java/com/connexta/replication/adapters/webhdfs/WebHdfsClientTest.java [hunk 2]
```diff
@@ -255,6 +256,25 @@ public void testUpdateResourceWithNoUpdates() throws URISyntaxException {
...
+
+    String originalFilename = String.format("%s_%s.txt", fileId, creationTime);
+
+    // when a file is created with ID fileId
+    CreateStorageRequest createStorageRequest =
+        generateTestStorageRequest(fileId, testName, new Date(creationTime));
+
+    adapter.createResource(createStorageRequest);
+
+    verifyFileContents(originalFilename, "my-data");
```
Comment (mdang8) [inline adapters/webhdfs-adapter/src/test/java/com/connexta/replication/adapters/webhdfs/WebHdfsClientTest.java]: It might be helpful to add a comment here about where the "my-data" string is coming from.

File: adapters/webhdfs-adapter/src/test/java/com/connexta/replication/adapters/webhdfs/WebHdfsClientTest.java [hunk 3]
```diff
@@ -306,15 +326,32 @@ private void verifyFileExists(String filename) throws URISyntaxException {
     }
 
     assertThat(hdfsLocalCluster.getHdfsFormat(), is(true));
-    assertThat(
-        uri.toString(),
-        is(
-            String.format(
-                "http://localhost:%s/webhdfs/v1/%s?op=GETFILESTATUS", HDFS_PORT, filename)));
+    assertThat(uri.toString(), is(String.format("%s%s?op=GETFILESTATUS", BASE_URL, filename)));
```
Comment (mdang8) [inline adapters/webhdfs-adapter/src/test/java/com/connexta/replication/adapters/webhdfs/WebHdfsClientTest.java]: Can you use the `url` variable here?

Comment (josephthweatt) [reply adapters/webhdfs-adapter/src/test/java/com/connexta/replication/adapters/webhdfs/WebHdfsClientTest.java]: url doesn't include the `op` parameter like uri does. Uri is built off of url though

Comment (mdang8) [reply adapters/webhdfs-adapter/src/test/java/com/connexta/replication/adapters/webhdfs/WebHdfsClientTest.java]: Oh I meant in the `is` part of that line. Like `is(String.format("%s?op=GETFILESTATUS", url)`

File: adapters/webhdfs-adapter/src/test/java/com/connexta/replication/adapters/webhdfs/WebHdfsClientTest.java (hunk 2 above)
Comment (josephthweatt) [reply adapters/webhdfs-adapter/src/test/java/com/connexta/replication/adapters/webhdfs/WebHdfsClientTest.java]: I'm replacing the string with a class constant

File: adapters/webhdfs-adapter/src/test/java/com/connexta/replication/adapters/webhdfs/WebHdfsClientTest.java (hunk 3 above)
Comment (mdang8) [reply adapters/webhdfs-adapter/src/test/java/com/connexta/replication/adapters/webhdfs/WebHdfsClientTest.java]: It depends what you're passing in for `filename` though. It won't work if it has a leading slash.

Comment (josephthweatt) [reply adapters/webhdfs-adapter/src/test/java/com/connexta/replication/adapters/webhdfs/WebHdfsClientTest.java]: Ah, got you

File: adapters/webhdfs-adapter/src/test/java/com/connexta/replication/adapters/webhdfs/WebHdfsClientTest.java [hunk 4]
```diff
@@ -306,15 +328,32 @@ private void verifyFileExists(String filename) throws URISyntaxException {
...
-        is(
-            String.format(
-                "http://localhost:%s/webhdfs/v1/%s?op=GETFILESTATUS", HDFS_PORT, filename)));
+    assertThat(uri.toString(), is(url));
     assertThat(fileStatus, notNullValue());
     assertThat(fileStatus.get("type"), is("FILE"));
   }
 
+  /**
+   * Utilizes the "Status of a File/Directory" WebHDFS operation to verify that the content within
```
Comment (cjlange) [inline adapters/webhdfs-adapter/src/test/java/com/connexta/replication/adapters/webhdfs/WebHdfsClientTest.java]: I would change this to say that it utilizes the "Open and Read a File" operation, because as written it implies that the method uses the `GETFILESTATUS` operation, which is inaccurate.

**Review by cjlange — CHANGES_REQUESTED** [review]

**Review by mdang8 — APPROVED** [review]

**Review by cjlange — APPROVED** [review]

**Comment by aaronilovici** [comment]
build now

**Comment by mdang8** [comment]
✅ Hero success!
