### PR TITLE
Fix WebHDFS adapter query to retry failed resources

### LINKED ISSUE #331: Implementation for retries in WebHDFS adapter
**Describe the task**
The WebHDFS adapter should include failed items in the query response.

**Additional context**

### PR DESCRIPTION
**Pull request by mdang8**
#### What does this PR do?

Fixes the query method for the WebHDFS adapter to include failed resources from previous replication runs. The `QueryRequest` passed to the query method contains a list of failed item IDs from the previous run of replication. These items should be included in the next run to retry creating them in DDF.

#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged)?

@cjlange 
@aaronilovici 
@josephthweatt 

#### How should this be tested? (List steps with links to updated documentation)

1. Build and install replication.
2. Configure a replication job with the HDFS instance as the source and DDF as the destination.
3. Upload some files to HDFS to be replicated.
4. Connect a remote debugger to DDF and set a breakpoint on line 302 in `DdfNodeAdapter`.
5. When the breakpoint gets hit, set the value of the `response` variable to `null`.
6. Resume execution in the debugger and verify an error for creating the metadata gets printed in the logs.
7. On the next replication run, verify a line gets printed in the logs that says "Found failed item IDs: [...]" with the failed ID inside the brackets.
8. Verify the failed item gets successfully replicated after that run.

#### Any background context you want to provide?

Integration tests are not included in this pull request.

#### What are the relevant tickets?
Fixes #331 

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

File: adapters/webhdfs-adapter/src/main/java/com/connexta/replication/adapters/webhdfs/WebHdfsNodeAdapter.java [hunk 1]
```diff
@@ -338,24 +346,50 @@ private String getVersion4Uuid(String fileUrl, Date modificationTime) {
...
+  List<FileStatus> getRelevantFiles(
+      List<FileStatus> files, List<String> failedItemIds, @Nullable Date filterDate) {
     files.removeIf(
-        file ->
-            file.isDirectory()
-                || (filterDate != null && !file.getModificationTime().after(filterDate)));
+        file -> {
+          // only need to do the lookup if there are items in the failed ID list
+          boolean isFailedId =
+              failedItemIds.isEmpty() ? false : checkIfFailedId(file, failedItemIds);
```
Comment (cjlange) [inline adapters/webhdfs-adapter/src/main/java/com/connexta/replication/adapters/webhdfs/WebHdfsNodeAdapter.java]: I have a few thoughts on this method and the `checkIfFailedId(...)` method.  There are some optimizations we could make, but I'll leave it up to you if you want to look into those for this pull request.  If you do, let's chat about the various options.

File: adapters/webhdfs-adapter/src/test/java/com/connexta/replication/adapters/webhdfs/WebHdfsNodeAdapterTest.java [hunk 2]
```diff
@@ -216,6 +220,105 @@ public void testQuery() throws IOException {
...
+        (int) StreamSupport.stream(metadataIterable.spliterator(), false).count();
+
+    assertThat(metadataIterableSize, is(4));
+    assertThat(
+        failedFile1Metadata.getResourceUri().toString(),
+        is(String.format("%s%s", WEBHDFS_URL, "failed-file1.ext")));
+    assertThat(
+        file1Metadata.getResourceUri().toString(),
+        is(String.format("%s%s", WEBHDFS_URL, "file1.ext")));
+  }
```
Comment (cjlange) [inline adapters/webhdfs-adapter/src/test/java/com/connexta/replication/adapters/webhdfs/WebHdfsNodeAdapterTest.java:325]: Could you add assertions related to the other metadata objects?

**Comment by cjlange** [comment]
build now

**Review by aaronilovici — COMMENTED** [review]
This LGTM, pending any changes coming from Chris.

**Review by josephthweatt — APPROVED** [review]

**Review by aaronilovici — APPROVED** [review]

File: adapters/webhdfs-adapter/src/main/java/com/connexta/replication/adapters/webhdfs/WebHdfsNodeAdapter.java [hunk 3]
```diff
@@ -338,22 +346,53 @@ private String getVersion4Uuid(String fileUrl, Date modificationTime) {
...
+        oldFiles.put(id, file);
+      }
+    }
+
+    return addFailedItemsToRelevantFiles(results, oldFiles, failedItemIds);
+  }
+
+  private List<FileStatus> addFailedItemsToRelevantFiles(List<FileStatus> relevantFiles, Map<String, FileStatus> oldFiles, List<String> failedItemIds) {
+    // only need to do the lookup if there are items in the failed ID list
+    if (oldFiles.isEmpty() || !failedItemIds.isEmpty()) {
```
Comment (aaronilovici) [inline adapters/webhdfs-adapter/src/main/java/com/connexta/replication/adapters/webhdfs/WebHdfsNodeAdapter.java]: Is this right? I'm having a hard time with this line for some reason.

Shouldn't we only want to go deeper if oldFiles list _isn't_ empty AND the failedItemIds list isn't empty?

Comment (mdang8) [reply adapters/webhdfs-adapter/src/main/java/com/connexta/replication/adapters/webhdfs/WebHdfsNodeAdapter.java]: It's not right

**Comment by mdang8** [comment]
build now please

File: adapters/webhdfs-adapter/src/main/java/com/connexta/replication/adapters/webhdfs/WebHdfsNodeAdapter.java [hunk 4]
```diff
@@ -345,9 +345,9 @@ String getVersion4Uuid(String fileUrl, Date modificationTime) {
   }
 
   /**
-   * Returns the files meeting the criteria for replication by removing elements that: 1) are of
-   * type DIRECTORY or 2) are not one of the failed IDs and have a modification time before or equal
-   * to the filter date, when the filter date is specified
+   * Returns the files meeting the criteria for replication by only including elements that: 1) are
+   * of type FILE or 2) are one of the failed IDs or 3) have a modification time after the filter
+   * date
```
Comment (cjlange) [inline adapters/webhdfs-adapter/src/main/java/com/connexta/replication/adapters/webhdfs/WebHdfsNodeAdapter.java]: Consider rephrasing this to indicate how the logic evaluation is grouped for better clarity.

`... only including elements that: 1) are of type FILE and 2) are one of the failed IDs or have a modification time after the filter date`

File: adapters/webhdfs-adapter/src/main/java/com/connexta/replication/adapters/webhdfs/WebHdfsNodeAdapter.java [hunk 5]
```diff
@@ -359,6 +359,9 @@ String getVersion4Uuid(String fileUrl, Date modificationTime) {
   List<FileStatus> getRelevantFiles(
       List<FileStatus> files, List<String> failedItemIds, @Nullable Date filterDate) {
     List<FileStatus> results = new ArrayList<>();
+
+    // this map contains the files that are after the filter date with UUID as keys and the
+    // associated FileStatus as values
```
Comment (cjlange) [inline adapters/webhdfs-adapter/src/main/java/com/connexta/replication/adapters/webhdfs/WebHdfsNodeAdapter.java]: This map is for files that were created before the filter date.

File: adapters/webhdfs-adapter/src/main/java/com/connexta/replication/adapters/webhdfs/WebHdfsNodeAdapter.java [hunk 6]
```diff
@@ -372,8 +375,7 @@ String getVersion4Uuid(String fileUrl, Date modificationTime) {
         results.add(file);
       } else {
         String fileUrl = getWebHdfsUrl().toString() + file.getPathSuffix();
-        Date modificationTime = file.getModificationTime();
-        String id = getVersion4Uuid(fileUrl, modificationTime);
+        String id = getVersion4Uuid(fileUrl, file.getModificationTime());
```
Comment (cjlange) [inline adapters/webhdfs-adapter/src/main/java/com/connexta/replication/adapters/webhdfs/WebHdfsNodeAdapter.java]: You could skip creating the `fileUrl` String and just pass the concatenated values directly.

File: adapters/webhdfs-adapter/src/main/java/com/connexta/replication/adapters/webhdfs/WebHdfsNodeAdapter.java [hunk 7]
```diff
@@ -382,9 +384,21 @@ String getVersion4Uuid(String fileUrl, Date modificationTime) {
     return addFailedItemsToRelevantFiles(results, oldFiles, failedItemIds);
   }
 
-  private List<FileStatus> addFailedItemsToRelevantFiles(List<FileStatus> relevantFiles, Map<String, FileStatus> oldFiles, List<String> failedItemIds) {
+  /**
+   * Iterates through the list of failed IDs to look up the associated {@link FileStatus} in the
+   * map.
+   *
+   * @param relevantFiles - the list of {@link FileStatus} to be returned
+   * @param oldFiles - the list of {@link FileStatus} with a modification date after the filter date
```
Comment (cjlange) [inline adapters/webhdfs-adapter/src/main/java/com/connexta/replication/adapters/webhdfs/WebHdfsNodeAdapter.java]: `oldFiles` contains files with mod date that occurred before the filter date.

File: adapters/webhdfs-adapter/src/main/java/com/connexta/replication/adapters/webhdfs/WebHdfsNodeAdapter.java [hunk 8]
```diff
@@ -382,9 +384,21 @@ String getVersion4Uuid(String fileUrl, Date modificationTime) {
...
+   * @param failedItemIds - the list of failed item IDs
+   * @return A list of {@link FileStatus} representing the full set of files to be returned
+   */
+  private List<FileStatus> addFailedItemsToRelevantFiles(
+      List<FileStatus> relevantFiles,
+      Map<String, FileStatus> oldFiles,
+      List<String> failedItemIds) {
     // only need to do the lookup if there are items in the failed ID list
```
Comment (cjlange) [inline adapters/webhdfs-adapter/src/main/java/com/connexta/replication/adapters/webhdfs/WebHdfsNodeAdapter.java]: If you want to keep this comment, you should add the criteria that old files are also required for a lookup to occur.

File: adapters/webhdfs-adapter/src/test/java/com/connexta/replication/adapters/webhdfs/WebHdfsNodeAdapterTest.java [hunk 9]
```diff
@@ -302,21 +302,27 @@ public void testQueryWithFailedItemIds() throws IOException {
 
     QueryResponse queryResponse = webHdfsNodeAdapter.query(queryRequest);
 
+    // expected sort order: failedFile2, failedFile1, file1, failedFile3
```
Comment (cjlange) [inline adapters/webhdfs-adapter/src/test/java/com/connexta/replication/adapters/webhdfs/WebHdfsNodeAdapterTest.java]: Remove this comment or clarify the expected sort order, as the names have changed.

**Review by cjlange — CHANGES_REQUESTED** [review]

File: adapters/webhdfs-adapter/src/main/java/com/connexta/replication/adapters/webhdfs/WebHdfsNodeAdapter.java (hunk 7 above)
Comment (mdang8) [reply adapters/webhdfs-adapter/src/main/java/com/connexta/replication/adapters/webhdfs/WebHdfsNodeAdapter.java]: Whoops I must be losing my mind making that mistake twice 😅

**Review by cjlange — APPROVED** [review]

**Comment by mdang8** [comment]
**build now** 🛠️

**Comment by josephthweatt** [comment]
Hero-ed successfully on my machine. LGTM!
