### PR TITLE
REP-119 Fix failure retry query bug

### LINKED ISSUE #119: When failure retries are included in csw query no new items are returned
**Describe the bug**
No new items are returned when querying over csw if the query contains search parameters for previously failed items. The matching failed items are returned however. 

The expected behavior is that new items would also be returned when we include failure items in the query as well. 

**Affects version**
0.2.x, 0.3.0

**To Reproduce**
1. Attempt to replicate a product that will fail
2. Ingest a new item that matches the filter criteria
3. attempt to replicate again
4. notice that the new item has not been replicated as it should be

**Expected behavior**
products matching the given filter will be replicated even when there are items in the repliction that previously failed.

### PR DESCRIPTION
**Pull request by kcover**
#### What does this PR do?
This commit fixes a bug where no new items are returned when failure
retries are included in a csw query to DDF

#### How should this be tested? (List steps with links to updated documentation)
Test steps are too long to list here and will likely change soon 😄. See me for information.
  
#### What are the relevant tickets?
Fixes #119 

#### Checklist:
- [ ] Documentation Updated
- [x] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

File: adapters/ddf-adapter/src/main/java/com/connexta/replication/adapters/ddf/DdfNodeAdapter.java [hunk 1]
```diff
@@ -261,13 +261,19 @@ public String getSystemName() {
...
-                queryRequest.getStartIndex(),
-                queryRequest.getPageSize()));
+    Iterable<Metadata> results;
+    // Failed items and new items are replicated separately due to a bug in DDF that was only fixed
+    // recently
+    if (queryRequest.getFailedItemIds().isEmpty()) {
+      results =
+          ResultIterable.resultIterable(this::getRecords, createDdfQueryRequest(queryRequest));
+    } else {
+      results =
```
Comment (clockard) [inline adapters/ddf-adapter/src/main/java/com/connexta/replication/adapters/ddf/DdfNodeAdapter.java]: if we made the createDdfFailedItemsQueryRequest just return null if there were no failed items and then had resultIterable just filter out null values it would simplify this. Not sure that it's worth it but just a thought.

Comment (kcover) [reply adapters/ddf-adapter/src/main/java/com/connexta/replication/adapters/ddf/DdfNodeAdapter.java]: I made the changes you suggested.

File: adapters/ddf-adapter/src/main/java/com/connexta/replication/adapters/ddf/ResultIterable.java [hunk 2]
```diff
@@ -179,9 +197,19 @@ private boolean isDistinctResult(@Nullable Metadata result) {
       return result != null && (result.getId() == null || !foundIds.contains(result.getId()));
     }
 
-    private void copyQueryRequestAndQuery(QueryRequest request, int index) {
+    private void nextRequestOrSignalFinished() {
```
Comment (paouelle) [inline adapters/ddf-adapter/src/main/java/com/connexta/replication/adapters/ddf/ResultIterable.java]: :question: Are we concerned by the recursion introduced between `fetchNextResults()` and `nextRequestOrSignalFinished()`? Should the logic be changed to avoid that?

Comment (kcover) [reply adapters/ddf-adapter/src/main/java/com/connexta/replication/adapters/ddf/ResultIterable.java]: I asked @clockard about that and we seemed to agree that It shouldn't be something we need to worry about. It should only be us using this class and I would hope none of us would put a few thousand query requests into the result iterable.

**Comment by clockard** [comment]
Heroed ✅
