### PR TITLE
REP-133 Make timeouts configurable

### LINKED ISSUE #133: Connections to DDF timeout for DFF instances that take longer than 60 seconds to respond
**Describe the bug**
It has come up that the default 60 second response time for querying DDF systems is timing out for very slow response systems. A mechanism needs to be added so that this timeout can be increased.

**Affects version**
0.2.2, 0.3.0

### PR DESCRIPTION
**Pull request by kcover**
#### What does this PR do?
Makes the connect and receive timeouts for any requests configurable via
application property. Also contains some refactoring.

#### How should this be tested? (List steps with links to updated documentation)
-Open the application.yml file you intend to use for configuring replication.
-Under `replication:` add a custom `connectionTimeout` and `receiveTimeout` in seconds. The defaults are 30 and 60 respectively.
-Add the following logging level changes under the logging level section
    `com.connexta.replication.adapters.ddf.DdfNodeAdapterFactory: DEBUG
    com.connexta.replication.adapters.ion.IonNodeAdapterFactory: DEBUG`
-Create the docker config
-Deploy the replication stack
-Check the logs (docker service logs -f repsync_ion-replication) and verify that the ddf and ion adapter factories were created with the custom timeouts

#### What are the relevant tickets?
Fixes #133 

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

File: commons/src/main/java/com/connexta/replication/spring/ReplicationProperties.java [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+  }
+
+  public void setPeriod(long period) {
+    this.period = period;
+  }
+
+  // We let the user set the connection timeout in seconds for readability but most clients take
+  // timeouts in milliseconds so we'll go ahead and do the conversion for them here.
+  public int getConnectionTimeout() {
+    if (connectionTimeout > 0) {
```
Comment (kcover) [inline commons/src/main/java/com/connexta/replication/spring/ReplicationProperties.java]: I should maybe test this code but it's not complex and I don't want the drop in code coverage caused by having jacoco analyze this module full of pojos.

File: adapters/ddf-adapter/src/main/java/com/connexta/replication/adapters/ddf/DdfNodeAdapterFactory.java [hunk 2]
```diff
@@ -13,32 +13,117 @@
...
+
   private final DdfRestClientFactory ddfRestClientFactory;
 
   private final ClientFactoryFactory clientFactory;
 
+  private final int connectionTimeout;
+
+  private final int receiveTimeout;
+
   public DdfNodeAdapterFactory(
```
Comment (paouelle) [inline adapters/ddf-adapter/src/main/java/com/connexta/replication/adapters/ddf/DdfNodeAdapterFactory.java]: ❗️ Javadoc missing

File: adapters/ddf-adapter/src/main/java/com/connexta/replication/adapters/ddf/DdfNodeAdapter.java [hunk 3]
```diff
@@ -104,65 +97,13 @@
 
   private SecureCxfClientFactory<Csw> factory;
 
-  private List<String> jaxbElementClassNames = new ArrayList<>();
-
-  private Map<String, String> jaxbElementClassMap = new HashMap<>();
-
   public DdfNodeAdapter(
```
Comment (paouelle) [inline adapters/ddf-adapter/src/main/java/com/connexta/replication/adapters/ddf/DdfNodeAdapter.java]: ❗️ Javadoc missing

File: adapters/ddf-adapter/src/main/java/com/connexta/replication/adapters/ddf/DdfNodeAdapterFactory.java [hunk 4]
```diff
@@ -13,32 +13,117 @@
...
+            connectionTimeout,
+            receiveTimeout);
+    return new DdfNodeAdapter(ddfRestClientFactory, ddfCswClientFactory, url);
+  }
+
+  private List<Object> initProviders() {
+
+    CswJAXBElementProvider getRecordsTypeProvider = new CswJAXBElementProvider<>();
+    getRecordsTypeProvider.setMarshallAsJaxbElement(true);
+    List<String> jaxbElementClassNames = new ArrayList<>();
```
Comment (paouelle) [inline adapters/ddf-adapter/src/main/java/com/connexta/replication/adapters/ddf/DdfNodeAdapterFactory.java]: ✏️ Can you create with a size of 5 based on what you use below? This will avoid allocating more memory than required.

File: adapters/ddf-adapter/src/main/java/com/connexta/replication/adapters/ddf/rest/DdfRestClientFactory.java [hunk 5]
```diff
@@ -27,8 +27,15 @@
 
   private final ClientFactoryFactory clientFactoryFactory;
 
-  public DdfRestClientFactory(ClientFactoryFactory clientFactoryFactory) {
+  private final int connectionTimeout;
+
+  private final int receiveTimeout;
+
+  public DdfRestClientFactory(
```
Comment (paouelle) [inline adapters/ddf-adapter/src/main/java/com/connexta/replication/adapters/ddf/rest/DdfRestClientFactory.java]: ❗️ Javadoc missing

File: adapters/ddf-adapter/src/main/java/com/connexta/replication/adapters/ddf/spring/ServiceConfig.java [hunk 6]
```diff
@@ -28,14 +28,12 @@ public ClientFactoryFactory clientFactoryFactory() {
     return new ClientFactoryFactoryImpl();
   }
 
-  @Bean
-  public DdfRestClientFactory ddfRestClientFactory(ClientFactoryFactory clientFactoryFactory) {
-    return new DdfRestClientFactory(clientFactoryFactory);
-  }
-
   @Bean
   public DdfNodeAdapterFactory ddfNodeAdapterFactory(
```
Comment (paouelle) [inline adapters/ddf-adapter/src/main/java/com/connexta/replication/adapters/ddf/spring/ServiceConfig.java]: ❗️ Javadoc missing

File: adapters/ion-adapter/src/main/java/com/connexta/replication/adapters/ion/IonNodeAdapterFactory.java [hunk 7]
```diff
@@ -19,19 +19,43 @@
 import org.codice.ditto.replication.api.NodeAdapter;
 import org.codice.ditto.replication.api.NodeAdapterFactory;
 import org.codice.ditto.replication.api.NodeAdapterType;
+import org.slf4j.Logger;
+import org.slf4j.LoggerFactory;
 import org.springframework.http.client.SimpleClientHttpRequestFactory;
 import org.springframework.web.client.RestTemplate;
 
 public class IonNodeAdapterFactory implements NodeAdapterFactory {
```
Comment (paouelle) [inline adapters/ion-adapter/src/main/java/com/connexta/replication/adapters/ion/IonNodeAdapterFactory.java]: ❗️ Javadoc missing

File: adapters/ion-adapter/src/main/java/com/connexta/replication/adapters/ion/IonNodeAdapterFactory.java [hunk 8]
```diff
@@ -19,19 +19,43 @@
...
 
+  private static final Logger LOGGER = LoggerFactory.getLogger(IonNodeAdapterFactory.class);
+
+  private final int connectionTimeout;
+
+  private final int receiveTimeout;
+
+  private final SimpleClientHttpRequestFactory requestFactory;
+
+  public IonNodeAdapterFactory(
```
Comment (paouelle) [inline adapters/ion-adapter/src/main/java/com/connexta/replication/adapters/ion/IonNodeAdapterFactory.java]: ❗️ Javadoc missing

File: adapters/ion-adapter/src/main/java/com/connexta/replication/adapters/ion/spring/ServiceConfig.java [hunk 9]
```diff
@@ -14,14 +14,19 @@
 package com.connexta.replication.adapters.ion.spring;
 
 import com.connexta.replication.adapters.ion.IonNodeAdapterFactory;
+import com.connexta.replication.spring.ReplicationProperties;
 import org.springframework.context.annotation.Bean;
 import org.springframework.context.annotation.Configuration;
+import org.springframework.http.client.SimpleClientHttpRequestFactory;
 
 @Configuration("ion-adapter")
 public class ServiceConfig {
```
Comment (paouelle) [inline adapters/ion-adapter/src/main/java/com/connexta/replication/adapters/ion/spring/ServiceConfig.java]: ❗️ Javadoc missing

File: adapters/ion-adapter/src/main/java/com/connexta/replication/adapters/ion/spring/ServiceConfig.java [hunk 10]
```diff
@@ -14,14 +14,19 @@
...
 
   @Bean
-  public IonNodeAdapterFactory ionNodeAdapterFactory() {
-    return new IonNodeAdapterFactory();
+  public IonNodeAdapterFactory ionNodeAdapterFactory(ReplicationProperties replicationProperties) {
```
Comment (paouelle) [inline adapters/ion-adapter/src/main/java/com/connexta/replication/adapters/ion/spring/ServiceConfig.java]: ❗️ Javadoc missing

File: commons/src/main/java/com/connexta/replication/spring/ReplicationProperties.java [hunk 11]
```diff
@@ -0,0 +1,50 @@
+package com.connexta.replication.spring;
+
+import java.util.concurrent.TimeUnit;
+import org.springframework.boot.context.properties.ConfigurationProperties;
+import org.springframework.stereotype.Component;
+
+@Component
+@ConfigurationProperties(prefix = "replication")
+public class ReplicationProperties {
```
Comment (paouelle) [inline commons/src/main/java/com/connexta/replication/spring/ReplicationProperties.java]: ❗️ Javadoc missing and all properties here are also missing javadoc

File: adapters/ddf-adapter/src/main/java/com/connexta/replication/adapters/ddf/spring/ServiceConfig.java (hunk 6 above)
Comment (kcover) [reply adapters/ddf-adapter/src/main/java/com/connexta/replication/adapters/ddf/spring/ServiceConfig.java]: I understand the class, but does the bean instantiation need javadoc?

Comment (paouelle) [reply adapters/ddf-adapter/src/main/java/com/connexta/replication/adapters/ddf/spring/ServiceConfig.java]: The method has parameters and those should be documented ... so yes

**Comment by clockard** [comment]
Heroed ✅
